### ISSUE TITLE
#US20 Sitio publicado en Servidor (OPCIONAL)

### ISSUE THREAD

**Issue by tefsantana** [Gaghyta/ProyectoIntegrador-E-COMMERCE#81]
Publicar sitio del proyecto en un servidor.

**Comment by MDLDeveloper** [comment]
Se buscó hosting web para subir el proyecto en https://www.pythonanywhere.com/, pero tuvimos inconveniente para implementarlo al no aceptar bien la implementación de Angular, después se averiguó una VPS prestada con Alojando Argentina ISP pero nunca más nos respondió.
